name: Cleanup

on:
  schedule:
    - cron: "00 5 * * 0" # build at 5:00 UTC weekly

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  delete-old-packages:
    name: Delete old packages
    runs-on: ubuntu-24.04
    permissions:
      packages: write # to delete packages
    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: ${{ github.repository }}
          package-type: container
          min-versions-to-keep: 10
